org.gradle.parallel=true
org.gradle.java.home=E:/JDK25

# Mod Properties
mod_name=MCA Inclusive Expressions
mod_version=4.5.1+26.3
maven_group=net.instantgratification
archives_base_name=mca-inclusive-expressions-addon

# Dependencies
minecraft_version=26.3-snapshot-6
minecraft_dependency=>=26.3-

# Fabric
fabric_version=0.156.1+26.3
fabric_loader_version=0.19.3

# Loom
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true

# DasikLibrary
dasik_library_version=1.8.39
